name: "kamchatka"
description: "A terminal agent that gives you full control of the context."
url: "https://github.com/ljedrz/nachalnik/tree/master/kamchatka"
docs: "https://github.com/ljedrz/nachalnik/tree/master/kamchatka"
tags:
  - coding
  - research
open_source: "https://github.com/ljedrz/nachalnik/tree/master/kamchatka"
date_added: "2026-09-24"
